### ISSUE TITLE
Move repo to openedx org

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/tutor-contrib-multi#6]

**Comment by antoviaque** [comment]
I've asked Sarina and Ed about this at https://github.com/openedx/open-edx-proposals/pull/372#issuecomment-1341552893

**Comment by antoviaque** [comment]
Support ticket created: https://github.com/openedx/tcril-engineering/issues/577

**Comment by antoviaque** [comment]
This is done! Thanks @Carlos-Muniz :+1: :partying_face:

**Comment by antoviaque** [comment]
Note that some of the permissions were dropped in the migration - see https://github.com/openedx/tutor-contrib-multi/issues/9

**Comment by bradenmacdonald** [comment]
@Carlos-Muniz  @antoviaque Thanks! I don't seem to have admin access anymore so can one of you please edit the repo description at the top right of https://github.com/openedx/tutor-contrib-multi (Under "About") to remove this part?

> Needs ... a new org home :)

You can leave in the part that it needs a new name, as it's more specific to [Open edX + Kubernetes] than [Tutor].

**Comment by Carlos-Muniz** [comment]
@bradenmacdonald Good catch! I've removed "a new org home" from this repo's About section.
